"""Generate, or check, the ADR index (``README.md``) of a workspace package's ``docs/adr/``.

Usage: ``python .github/scripts/adr_index.py [--check] [--compiler <adr-dir>] [<adr-dir>...]``

``--compiler`` marks the compiler's own ``docs/adr/`` (repository-wide numbers); the others are
workspace members' (numbers local to the package).

Each ``NNNN-title.md`` other than ``0000-template.md`` contributes one row: its number, the title
from its ``# NNNN — Title`` heading and the value of its ``- Status:`` line, followed by
``amended by NNNN`` (compiler index only) for every other ADR whose ``- Amends:`` header names it.
The index is generated so concurrent PRs that each add an ADR never conflict on a hand-edited
table; they regenerate it after merging main. With ``--check`` nothing is written and the exit
status is 1 if any index is stale. Standard library only, so CI can run it before anything is
installed.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

INDEX = "README.md"
TEMPLATE = "0000-template.md"
_ADR_FILE = re.compile(r"^(\d{4})-.+\.md$")
_HEADING = re.compile(r"^#\s+\d{4}\s+[—-]+\s+(?P<title>.+?)\s*$")
_STATUS = re.compile(r"^-\s+Status:\s*(?P<status>.+?)\s*$")
_AMENDS = re.compile(r"^-\s+Amends:\s*(?P<text>.*)$")
_ADR_REF = re.compile(r"\bADR (\d{4})\b")

COMPILER_HEADER = """\
# Architecture Decision Records

<!-- Generated by `make adr-index` from the ADR files; do not edit by hand. -->

One decision per file, `NNNN-short-title.md`, using `0000-template.md`. Decisions are superseded by
a new ADR that links back; they are never edited in place. Status values: Proposed, Accepted,
Superseded by NNNN. A decision another ADR amends shows "amended by NNNN" (from that ADR's `Amends:`
header).

| ADR | Title | Status |
|---|---|---|
"""

HEADER = """\
# Architecture Decision Records

<!-- Generated by `make adr-index` from the ADR files; do not edit by hand. -->

One decision per file, `NNNN-short-title.md`, using `0000-template.md`. Numbers are local to
this package. Decisions are superseded by a new ADR that links back; never edited in place.

| ADR | Title | Status |
|---|---|---|
"""


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def _first_clause(text: str) -> str:
    """``text`` up to the first ``;`` outside parentheses ("Amends: X; settles Y" amends only X)."""
    depth = 0
    for index, char in enumerate(text):
        depth += (char == "(") - (char == ")")
        if char == ";" and depth <= 0:
            return text[:index]
    return text


def _amended_by(adr_dir: Path) -> dict[str, list[str]]:
    """Map an ADR number to the numbers of the ADRs whose ``Amends:`` header names it."""
    amended: dict[str, set[str]] = {}
    for path in sorted(adr_dir.iterdir()):
        match = _ADR_FILE.match(path.name)
        if match is None or path.name == TEMPLATE:
            continue
        text = ""
        in_item = False
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith("## "):
                break
            if found := _AMENDS.match(line):
                text, in_item = found["text"], True
            elif in_item and line.startswith("  "):  # a wrapped continuation of the item
                text += " " + line.strip()
            else:
                in_item = False
        for target in _ADR_REF.findall(_first_clause(text)):
            if target != match[1]:
                amended.setdefault(target, set()).add(match[1])
    return {target: sorted(by) for target, by in amended.items()}


def render(adr_dir: Path, *, compiler: bool = False) -> str:
    """The index document for ``adr_dir``, as text."""
    amended = _amended_by(adr_dir) if compiler else {}
    rows: list[str] = []
    for path in sorted(adr_dir.iterdir()):
        match = _ADR_FILE.match(path.name)
        if match is None or path.name == TEMPLATE:
            continue
        title = status = "?"
        for line in path.read_text(encoding="utf-8").splitlines():
            if title == "?" and (heading := _HEADING.match(line)):
                title = heading["title"]
            elif status == "?" and (found := _STATUS.match(line)):
                status = found["status"]
        by = [n for n in amended.get(match[1], []) if n not in status]
        if by:
            status += f"; amended by {', '.join(by)}"
        rows.append(f"| [{match[1]}]({path.name}) | {_cell(title)} | {_cell(status)} |\n")
    header = COMPILER_HEADER if compiler else HEADER
    return header + ("".join(rows) if rows else "| — | _No decisions yet._ | — |\n")


def main(argv: list[str]) -> int:
    check = "--check" in argv
    args = [arg for arg in argv if arg != "--check"]
    targets: list[tuple[Path, bool]] = []
    while args:
        arg = args.pop(0)
        if arg == "--compiler" and args:
            targets.append((Path(args.pop(0)), True))
        else:
            targets.append((Path(arg), False))
    if not targets:
        sys.stderr.write("usage: adr_index.py [--check] [--compiler <adr-dir>] [<adr-dir>...]\n")
        return 2
    stale: list[Path] = []
    for adr_dir, compiler in targets:
        index = adr_dir / INDEX
        expected = render(adr_dir, compiler=compiler)
        current = index.read_text(encoding="utf-8") if index.is_file() else None
        if current == expected:
            continue
        if check:
            stale.append(index)
        else:
            index.write_text(expected, encoding="utf-8")
    for index in stale:
        sys.stderr.write(f"{index} is stale; run `make adr-index`\n")
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
