"""Generate, or check, the ADR index (``README.md``) of a workspace package's ``docs/adr/``.

Usage: ``python .github/scripts/adr_index.py [--check] <adr-dir>...``

Each ``NNNN-title.md`` other than ``0000-template.md`` contributes one row: its number, the title
from its ``# NNNN — Title`` heading and the value of its ``- Status:`` line. The index is generated
so concurrent PRs that each add an ADR never conflict on a hand-edited table; they regenerate it
after merging main. With ``--check`` nothing is written and the exit status is 1 if any index is
stale. Standard library only, so CI can run it before anything is installed.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

INDEX = "README.md"
TEMPLATE = "0000-template.md"
_ADR_FILE = re.compile(r"^(\d{4})-.+\.md$")
_HEADING = re.compile(r"^#\s+\d{4}\s+[—-]+\s+(?P<title>.+?)\s*$")
_STATUS = re.compile(r"^-\s+Status:\s*(?P<status>.+?)\s*$")

HEADER = """\
# Architecture Decision Records

<!-- Generated by `make adr-index` from the ADR files; do not edit by hand. -->

One decision per file, `NNNN-short-title.md`, using `0000-template.md`. Numbers are local to
this package. Decisions are superseded by a new ADR that links back; never edited in place.

| ADR | Title | Status |
|---|---|---|
"""


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def render(adr_dir: Path) -> str:
    """The index document for ``adr_dir``, as text."""
    rows: list[str] = []
    for path in sorted(adr_dir.iterdir()):
        match = _ADR_FILE.match(path.name)
        if match is None or path.name == TEMPLATE:
            continue
        title = status = "?"
        for line in path.read_text(encoding="utf-8").splitlines():
            if title == "?" and (heading := _HEADING.match(line)):
                title = heading["title"]
            elif status == "?" and (found := _STATUS.match(line)):
                status = found["status"]
        rows.append(f"| [{match[1]}]({path.name}) | {_cell(title)} | {_cell(status)} |\n")
    return HEADER + ("".join(rows) if rows else "| — | _No decisions yet._ | — |\n")


def main(argv: list[str]) -> int:
    check = "--check" in argv
    dirs = [Path(arg) for arg in argv if arg != "--check"]
    if not dirs:
        sys.stderr.write("usage: adr_index.py [--check] <adr-dir>...\n")
        return 2
    stale: list[Path] = []
    for adr_dir in dirs:
        index = adr_dir / INDEX
        expected = render(adr_dir)
        current = index.read_text(encoding="utf-8") if index.is_file() else None
        if current == expected:
            continue
        if check:
            stale.append(index)
        else:
            index.write_text(expected, encoding="utf-8")
    for index in stale:
        sys.stderr.write(f"{index} is stale; run `make adr-index`\n")
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
