"""Lockfiles: the dependency set a resolver pinned, one item per locked package (ADR 0040).

Every lockfile is one ``SoftwareConfiguration`` (the set is one declaration), ``stated``. Each
package is an item with its ``name`` and ``release`` as locked: SemVer where the format makes it
so (Cargo), declared text otherwise (PEP 440 for uv and Poetry, node-semver ranges' loose syntax
for npm). A package fetched from git carries the commit the lockfile pinned: the ``#<commit>``
fragment of a Cargo, uv or npm git source (cited as a ``Span`` of that string) or Poetry's
``resolved_reference``. Archive hashes describe package archives, which ``digest``'s kinds do not
(``NotApplicable``); they stay cited in the item's bytes.

- **Cargo.lock** and **poetry.lock** start with their tool's ``@generated`` header; **uv.lock** is
  TOML with top-level ``version`` and ``requires-python``. Each ``[[package]]`` is an item.
- **package-lock.json** (``lockfileVersion`` 1 to 3): each ``packages`` entry is an item, named by
  its ``name`` or else by its folder key after the last ``node_modules/`` (npm's layout); the
  root ``""`` entry falls back to the top-level ``name``. A ``link`` entry points at another entry
  and is not an item. Version 1 files list ``dependencies`` recursively, read in pre-order.
"""

import re
from collections.abc import Callable, Iterator
from typing import Any, Final

from neptune.adapters.contract import SIGNATURE, VERIFIED, FormatSpec
from neptune.adapters.software._common import (
    Detected,
    Doc,
    Draft,
    Format,
    Reading,
    json_head,
    reason,
    toml_head,
)
from neptune.model.knowledge import AssertionKind, Knowledge
from neptune.model.machine import Release
from neptune.model.provenance import ByteRange, EvidenceRef, Span
from neptune.model.versions import GitCommit

_CARGO_HEADER: Final = b"# This file is automatically @generated by Cargo."
_POETRY_HEADER: Final = b"# This file is automatically @generated by Poetry"
_FRAGMENT: Final = re.compile(r"#([0-9a-fA-F]+)$")
_NPM_VERSION: Final = re.compile(rb'"lockfileVersion"\s*:\s*([0-9]+)')


def _git_fragment(
    reading: Reading, draft: Draft, text: object, at: EvidenceRef
) -> Knowledge[GitCommit] | None:
    """The commit a ``git+<url>#<commit>`` source pins, citing its span; ``None`` if none."""
    if not isinstance(text, str):
        return None
    match = _FRAGMENT.search(text)
    if match is None:
        return None
    spanned = reading.at(*at.locator, Span(match.start(1), match.end(1)))
    return reading.value(draft, "commit", match[1], spanned, GitCommit, "git object name")


def _package(
    reading: Reading,
    doc: Doc,
    path: tuple[str | int, ...],
    entry: dict[str, Any],
    release: Callable[[Reading, Draft, object, EvidenceRef], Knowledge[Release]],
) -> Draft:
    at = doc.ref(*path)
    draft = Draft(entry=at)
    draft.name = reading.text(
        draft, "name", entry.get("name"), doc.ref(*path, "name") if "name" in entry else at
    )
    version_at = doc.ref(*path, "version") if "version" in entry else at
    draft.release = release(reading, draft, entry.get("version"), version_at)
    return draft


def _declared(reading: Reading, draft: Draft, raw: object, at: EvidenceRef) -> Knowledge[Release]:
    return reading.declared(draft, raw, at)


def _semver(reading: Reading, draft: Draft, raw: object, at: EvidenceRef) -> Knowledge[Release]:
    return reading.semver(draft, raw, at)


def _toml_packages(reading: Reading) -> tuple[Doc, list[tuple[int, dict[str, Any]]]] | None:
    data = reading.toml()
    if data is None:
        return None
    packages = data.get("package", [])
    doc = Doc(reading, (ByteRange(0, reading.source.size),))
    if not isinstance(packages, list):
        reading.malformed("has a package key that is not an array of tables")
        return None
    entries: list[tuple[int, dict[str, Any]]] = []
    for index, entry in enumerate(packages):
        if isinstance(entry, dict):
            entries.append((index, entry))
        else:
            reading.malformed_entry(doc.ref("package", index), "is not a table")
    return doc, entries


def _read_cargo_lock(reading: Reading) -> list[Draft]:
    found = _toml_packages(reading)
    if found is None:
        return []
    doc, entries = found
    drafts = []
    for index, entry in entries:
        draft = _package(reading, doc, ("package", index), entry, _semver)
        source = entry.get("source")
        if isinstance(source, str) and source.startswith("git+"):
            commit = _git_fragment(reading, draft, source, doc.ref("package", index, "source"))
            if commit is not None:
                draft.commit = commit
        drafts.append(draft)
    return drafts


def _read_uv_lock(reading: Reading) -> list[Draft]:
    found = _toml_packages(reading)
    if found is None:
        return []
    doc, entries = found
    drafts = []
    for index, entry in entries:
        draft = _package(reading, doc, ("package", index), entry, _declared)
        source = entry.get("source")
        if isinstance(source, dict) and "git" in source:
            commit = _git_fragment(
                reading, draft, source["git"], doc.ref("package", index, "source", "git")
            )
            if commit is not None:
                draft.commit = commit
        drafts.append(draft)
    return drafts


def _read_poetry_lock(reading: Reading) -> list[Draft]:
    found = _toml_packages(reading)
    if found is None:
        return []
    doc, entries = found
    drafts = []
    for index, entry in entries:
        draft = _package(reading, doc, ("package", index), entry, _declared)
        source = entry.get("source")
        if isinstance(source, dict) and source.get("type") == "git":
            path = ("package", index, "source")
            at = (
                doc.ref(*path, "resolved_reference")
                if "resolved_reference" in source
                else doc.ref(*path)
            )
            draft.commit = reading.value(
                draft, "commit", source.get("resolved_reference"), at, GitCommit, "git object name"
            )
        drafts.append(draft)
    return drafts


def _npm_entry(
    reading: Reading,
    doc: Doc,
    path: tuple[str | int, ...],
    entry: dict[str, Any],
    name: str | None,
    name_at: EvidenceRef,
) -> Draft:
    draft = _package(reading, doc, path, entry, _declared)
    if "name" not in entry:
        draft.name = reading.text(draft, "name", name, name_at)
    resolved = entry.get("resolved")
    if isinstance(resolved, str) and resolved.startswith("git+"):
        commit = _git_fragment(reading, draft, resolved, doc.ref(*path, "resolved"))
        if commit is not None:
            draft.commit = commit
    return draft


def _npm_v1(
    reading: Reading, doc: Doc, dependencies: dict[str, Any], limit: int
) -> Iterator[Draft]:
    stack: list[tuple[tuple[str | int, ...], Iterator[tuple[str, Any]]]] = [
        (("dependencies",), iter(dependencies.items()))
    ]
    emitted = 0
    while stack and emitted <= limit:
        path, entries = stack[-1]
        following = next(entries, None)
        if following is None:
            stack.pop()
            continue
        name, entry = following
        if not isinstance(entry, dict):
            reading.malformed_entry(doc.ref(*path, name), "is not an object")
            continue
        yield _npm_entry(reading, doc, (*path, name), entry, name, doc.ref(*path, name))
        emitted += 1
        children = entry.get("dependencies")
        if isinstance(children, dict):
            stack.append(((*path, name, "dependencies"), iter(children.items())))


def _read_npm(reading: Reading) -> list[Draft]:
    data = reading.json(reading.document())
    if data is None:
        return []
    if not isinstance(data, dict):
        reading.malformed("is not a JSON object")
        return []
    doc = Doc(reading, (ByteRange(0, reading.source.size),))
    limit = reading.config.integer("max_items")
    drafts: list[Draft] = []
    packages = data.get("packages")
    top_name_at = doc.ref("name") if "name" in data else doc.ref()
    if isinstance(packages, dict):
        for key, entry in packages.items():
            if len(drafts) > limit:
                break
            if not isinstance(entry, dict):
                reading.malformed_entry(doc.ref("packages", key), "is not an object")
                continue
            if entry.get("link") is True:
                continue
            if key == "":
                name, name_at = data.get("name"), top_name_at
            else:
                name, name_at = key.rsplit("node_modules/", 1)[-1], doc.ref("packages", key)
            drafts.append(_npm_entry(reading, doc, ("packages", key), entry, name, name_at))
    elif isinstance(data.get("dependencies"), dict):
        root = Draft(entry=doc.ref())
        root.name = reading.text(root, "name", data.get("name"), top_name_at)
        version_at = doc.ref("version") if "version" in data else doc.ref()
        root.release = reading.declared(root, data.get("version"), version_at)
        drafts = [root, *_npm_v1(reading, doc, data["dependencies"], limit)]
    return drafts


def _detect_toml_lock(
    header: bytes, key: str, what: str
) -> Callable[[bytes, int], Detected | None]:
    def detect(head: bytes, size: int) -> Detected | None:
        if not head.startswith(header):
            return None
        document = toml_head(head, size)
        if document is not None and isinstance(document.get("package", []), list):
            return Detected(
                VERIFIED, reason(key, f"{what}'s @generated header, and its TOML parses")
            )
        return Detected(SIGNATURE, reason(key, f"{what}'s @generated header"))

    return detect


_UV_KEYS: Final = (
    re.compile(rb"^version = [0-9]+$", re.M),
    re.compile(rb"^requires-python = \"", re.M),
    re.compile(rb"^\[\[package\]\]$", re.M),
)


def _detect_uv(head: bytes, size: int) -> Detected | None:
    if not all(key.search(head) for key in _UV_KEYS):
        return None
    document = toml_head(head, size)
    if document is None:
        why = "uv.lock's top-level version and requires-python, and [[package]] tables"
        return Detected(SIGNATURE, reason("uv_lock", why))
    version, python = document.get("version"), document.get("requires-python")
    if isinstance(version, int) and isinstance(python, str):
        return Detected(
            VERIFIED,
            reason("uv_lock", "TOML with uv.lock's version and requires-python"),
            str(version),
        )
    return None


def _detect_npm(head: bytes, size: int) -> Detected | None:
    if not head.lstrip().startswith(b"{"):
        return None
    match = _NPM_VERSION.search(head)
    if match is None:
        return None
    version = match[1].decode("ascii")
    document = json_head(head, size)
    if isinstance(document, dict) and isinstance(document.get("lockfileVersion"), int):
        why = reason("npm_lock", "a package-lock.json that parses, with its lockfileVersion")
        return Detected(VERIFIED, why, version)
    return Detected(
        SIGNATURE, reason("npm_lock", "a JSON object with npm's lockfileVersion"), version
    )


CARGO_LOCK: Final = Format(
    key="cargo_lock",
    label="Cargo.lock",
    spec=FormatSpec("Cargo lockfile (Cargo.lock)"),
    assertion=AssertionKind.STATED,
    detect=_detect_toml_lock(_CARGO_HEADER, "cargo_lock", "Cargo"),
    read=_read_cargo_lock,
)
POETRY_LOCK: Final = Format(
    key="poetry_lock",
    label="poetry.lock",
    spec=FormatSpec("Poetry lockfile (poetry.lock)"),
    assertion=AssertionKind.STATED,
    detect=_detect_toml_lock(_POETRY_HEADER, "poetry_lock", "Poetry"),
    read=_read_poetry_lock,
)
UV_LOCK: Final = Format(
    key="uv_lock",
    label="uv.lock",
    spec=FormatSpec("uv lockfile (uv.lock)"),
    assertion=AssertionKind.STATED,
    detect=_detect_uv,
    read=_read_uv_lock,
)
NPM_LOCK: Final = Format(
    key="npm_lock",
    label="package-lock.json",
    spec=FormatSpec("npm lockfile (package-lock.json)"),
    assertion=AssertionKind.STATED,
    detect=_detect_npm,
    read=_read_npm,
)
