-- 0004 record projections for urn:neptune:schema:canonical:1 (Ledger ADR 0008).
--
-- GENERATED by neptune_ledger.catalog.projection from the package schema's JSON Schema
-- export; do not edit. A schema bump regenerates projections.json and writes the next
-- migration; this one is never rewritten. Columns go on the partitioned parent, so
-- every partition has them; only the kinds listed below fill them, and NULL means the
-- record does not state the value as Known (the package keeps its state).
--
-- Hot-filter projections this migration adds (kind.field -> columns):
--   asset.site -> site_namespace, site_value
--   calibration.machine -> machine_namespace, machine_value
--   hardware_configuration.machine -> machine_namespace, machine_value
--   run.machine -> machine_namespace, machine_value
--   software_configuration.machine -> machine_namespace, machine_value
--   stream.clocks -> clock_ids
--   stream.run -> run_ids
--   video.clock -> clock_ids

ALTER TABLE record ADD COLUMN clock_ids text[];
CREATE INDEX record_by_clock_ids ON record USING gin (clock_ids)
  WHERE clock_ids IS NOT NULL;

ALTER TABLE record ADD COLUMN machine_namespace text, ADD COLUMN machine_value text,
  ADD CONSTRAINT record_machine_whole
  CHECK ((machine_namespace IS NULL) = (machine_value IS NULL));
CREATE INDEX record_by_machine ON record (machine_namespace, machine_value, kind)
  WHERE machine_value IS NOT NULL;

ALTER TABLE record ADD COLUMN run_ids text[];
CREATE INDEX record_by_run_ids ON record USING gin (run_ids)
  WHERE run_ids IS NOT NULL;

ALTER TABLE record ADD COLUMN site_namespace text, ADD COLUMN site_value text,
  ADD CONSTRAINT record_site_whole
  CHECK ((site_namespace IS NULL) = (site_value IS NULL));
CREATE INDEX record_by_site ON record (site_namespace, site_value, kind)
  WHERE site_value IS NOT NULL;
