-- 0006 record projections for urn:neptune:schema:canonical:4 (Ledger ADR 0009).
--
-- GENERATED by neptune_ledger.catalog.projection from the package schema's JSON Schema
-- export; do not edit. A schema bump regenerates projections.json and writes the next
-- migration; this one is never rewritten. Columns go on the partitioned parent, so
-- every partition has them; only the kinds listed below fill them, and NULL means the
-- record does not state the value as Known (the package keeps its state).
--
-- Hot-filter projections this migration adds (kind.field -> columns):
--   authorisation_envelope.site -> site_namespace, site_value
--   change_record.site -> site_namespace, site_value
--   commissioning_baseline.site -> site_namespace, site_value
--   incident_record.site -> site_namespace, site_value
--   intervention.site -> site_namespace, site_value
--   maintenance_event.site -> site_namespace, site_value
--   requalification_record.site -> site_namespace, site_value
--   risk_assessment.site -> site_namespace, site_value
--   run_assembly.run -> run_ids
--   snapshot_binding.run -> run_ids

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM record WHERE kind IN ('authorisation_envelope', 'change_record', 'commissioning_baseline', 'incident_record', 'intervention', 'maintenance_event', 'requalification_record', 'risk_assessment', 'run_assembly', 'snapshot_binding')) THEN
    RAISE EXCEPTION 'record rows of a kind gaining a projection would read as not'
      ' Known; rebuild this catalog from its packages and registration log (ADR 0009)';
  END IF;
END
$$;
