-- 0010 record projections for urn:neptune:schema:canonical:7 (Ledger ADR 0009).
--
-- GENERATED by neptune_ledger.catalog.projection from the package schema's JSON Schema
-- export; do not edit. A schema bump regenerates projections.json and writes the next
-- migration; this one is never rewritten. Columns go on the partitioned parent, so
-- every partition has them; only the kinds listed below fill them, and NULL means the
-- record does not state the value as Known (the package keeps its state).
--
-- Hot-filter projections this migration adds (kind.field -> columns):
--   task_brief.site -> site_namespace, site_value
--   work_order.site -> site_namespace, site_value

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM record WHERE kind IN ('task_brief', 'work_order')) THEN
    RAISE EXCEPTION 'record rows of a kind gaining a projection would read as not'
      ' Known; rebuild this catalog from its packages and registration log (ADR 0009)';
  END IF;
END
$$;
