"""What the software adapter reads from each format, value by value (ADR 0040).

The fixtures are generated by ``tests/fixtures/software/make_software_fixtures.py``; the values
asserted here are the generator's constants, and ``software_oracle.check_citations`` (run on every
fixture by ``test_software_adapter.py``) proves each value is where it cites.
"""

import importlib.util
import sys
from pathlib import Path
from types import ModuleType
from typing import Any, Final

from neptune.adapters.harness import SourceOutput
from neptune.identity.hashing import content_id
from neptune.model.knowledge import Ambiguous, AssertionKind, Known, Unknown
from neptune.model.machine import SoftwareConfiguration, SoftwareItem
from neptune.model.provenance import ByteRange, JsonPointer, Provenance, Span
from neptune.model.versions import (
    BuildId,
    ContainerImageDigest,
    DeclaredVersion,
    FirmwareVersion,
    GitCommit,
    HashAlgorithm,
    ModelCheckpointHash,
    SemanticVersion,
)


def _load(name: str) -> ModuleType:
    path = Path(__file__).parents[2] / "fixtures" / "software" / f"{name}.py"
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


ORACLE: Final = _load("software_oracle")
MAKE: Final = _load("make_software_fixtures")


def read(relative: str, **config: Any) -> SourceOutput:
    output: SourceOutput = ORACLE.run(ORACLE.fixture(relative), **config)
    return output


def items(output: SourceOutput) -> list[SoftwareItem]:
    found: list[SoftwareItem] = ORACLE.items(output)
    return found


def codes(output: SourceOutput) -> list[str]:
    found: list[str] = ORACLE.codes(output)
    return found


def value(state: object) -> object:
    assert isinstance(state, Known), state
    return state.value


def record(output: SourceOutput) -> SoftwareConfiguration:
    (found,) = output.records()
    assert isinstance(found, SoftwareConfiguration)
    return found


def assertion(output: SourceOutput) -> AssertionKind:
    return record(output).provenance.assertion_kind


# --- Git ---------------------------------------------------------------------------------------


def test_a_detached_head_is_its_commit_observed() -> None:
    output = read("git/HEAD_detached")
    (item,) = items(output)
    assert value(item.commit) == GitCommit(MAKE.SHA_MAIN)
    assert item.name.state == item.release.state == item.build.state == "not_covered"
    assert item.digest.state == "not_applicable"
    assert assertion(output) is AssertionKind.OBSERVED
    assert codes(output) == []


def test_a_symbolic_ref_names_its_ref_for_binding_and_makes_no_record() -> None:
    output = read("git/HEAD")
    assert output.records() == ()
    (finding,) = output.findings()
    assert finding.code == "software.git_symbolic_ref"
    assert finding.details == {"target": "refs/heads/main"}
    assert finding.subject.locator == (ByteRange(5, len("refs/heads/main")),)  # type: ignore[union-attr]


def test_packed_refs_are_an_item_per_ref_with_tags_peeled() -> None:
    output = read("git/packed-refs")
    found = {value(item.name): value(item.commit) for item in items(output)}
    assert found == {
        "refs/heads/main": GitCommit(MAKE.SHA_MAIN),
        "refs/remotes/origin/dev": GitCommit(MAKE.SHA_DEV),
        "refs/tags/v1.4.2": GitCommit(MAKE.SHA_TAG_COMMIT),  # the ^ line, not the tag object
    }
    assert codes(output) == []


def test_a_tag_in_old_packed_refs_may_be_a_tag_object_so_its_commit_is_unknown() -> None:
    output = read("git/packed-refs_unpeeled")
    main, tag = items(output)
    assert value(main.commit) == GitCommit(MAKE.SHA_MAIN)
    assert isinstance(tag.commit, Unknown)
    assert codes(output) == ["git_unpeeled_tag"]  # the identity gap is explained, not doubled


def test_corrupt_packed_ref_lines_are_skipped_and_the_rest_read() -> None:
    output = read("git/packed-refs_corrupt")
    (item,) = items(output)
    assert value(item.name) == "refs/heads/main"
    assert codes(output) == ["malformed_entry", "malformed_entry"]


# --- Build manifests ---------------------------------------------------------------------------


def test_a_ros_package_xml_is_a_name_and_a_semver_release_stated() -> None:
    output = read("manifests/package.xml")
    (item,) = items(output)
    assert value(item.name) == "arm_controller"
    assert value(item.release) == SemanticVersion("2.1.0")
    assert item.commit.state == item.build.state == "not_covered"
    assert assertion(output) is AssertionKind.STATED
    assert isinstance(item.release, Known) and isinstance(item.release.provenance, Provenance)
    (step,) = item.release.provenance.evidence.locator
    assert isinstance(step, ByteRange)
    assert ORACLE.fixture("manifests/package.xml")[step.offset : step.offset + step.length] == (
        b"<version>2.1.0</version>"
    )


def test_a_package_version_that_is_not_semver_is_kept_as_declared_text() -> None:
    output = read("manifests/package_bad_version.xml")
    (item,) = items(output)
    assert value(item.release) == DeclaredVersion("2.1")
    assert codes(output) == ["version_not_semver"]


def test_xml_entities_and_cut_documents_are_malformed() -> None:
    assert codes(read("manifests/package_entity.xml")) == ["malformed"]
    assert codes(read("manifests/package_truncated.xml")) == ["malformed"]


def test_pyproject_values_cite_their_pointers() -> None:
    output = read("manifests/pyproject.toml")
    (item,) = items(output)
    assert value(item.name) == "grasp-planner"
    assert value(item.release) == DeclaredVersion("0.7.3")  # PEP 440, not SemVer
    assert isinstance(item.release, Known) and isinstance(item.release.provenance, Provenance)
    assert item.release.provenance.evidence.locator[1] == JsonPointer("/project/version")


def test_a_dynamic_version_is_unknown_and_said_why_once() -> None:
    output = read("manifests/pyproject_dynamic.toml")
    (item,) = items(output)
    assert isinstance(item.release, Unknown)
    assert codes(output) == ["unevaluated"]


def test_project_and_poetry_tables_that_disagree_are_ambiguous() -> None:
    output = read("manifests/pyproject_conflict.toml")
    (item,) = items(output)
    assert value(item.name) == "grasp-planner"  # both tables agree: one value
    assert isinstance(item.release, Ambiguous)
    assert [c.value for c in item.release.candidates] == [
        DeclaredVersion("0.7.3"),
        DeclaredVersion("0.7.4"),
    ]
    assert codes(output) == ["conflicting_identity"]


def test_cargo_manifests_are_semver_and_inheritance_is_unevaluated() -> None:
    (item,) = items(read("manifests/Cargo.toml"))
    assert value(item.release) == SemanticVersion("0.3.1")
    member = read("manifests/Cargo_member.toml")
    (inherited,) = items(member)
    assert isinstance(inherited.release, Unknown)
    assert codes(member) == ["unevaluated"]


def test_cmake_project_arguments_are_read_without_evaluation() -> None:
    output = read("manifests/CMakeLists.txt")
    (item,) = items(output)
    assert value(item.name) == "lidar_driver"
    assert value(item.release) == DeclaredVersion("1.8.0")
    variable = read("manifests/CMakeLists_variable.txt")
    (unknown,) = items(variable)
    assert isinstance(unknown.name, Unknown) and isinstance(unknown.release, Unknown)
    assert codes(variable) == ["unevaluated", "unevaluated"]
    assert codes(read("manifests/CMakeLists_unterminated.txt")) == ["malformed"]


def test_setup_py_literals_are_read_and_code_is_never_run() -> None:
    (item,) = items(read("manifests/setup_py"))
    assert (value(item.name), value(item.release)) == (
        "perception_utils",
        DeclaredVersion("0.9.0"),
    )
    dynamic = read("manifests/setup_dynamic_py")
    (unknown,) = items(dynamic)
    assert isinstance(unknown.release, Unknown)
    assert codes(dynamic) == ["unevaluated"]
    assert codes(read("manifests/setup_broken_py")) == ["malformed"]


# --- Lockfiles ---------------------------------------------------------------------------------


def test_uv_lock_is_an_item_per_package_with_git_commits_as_spans() -> None:
    output = read("lockfiles/uv.lock")
    planner, solver, numpy = items(output)
    assert value(numpy.name) == "numpy" and value(numpy.release) == DeclaredVersion("2.1.0")
    assert numpy.digest.state == "not_applicable"  # an archive hash is no checkpoint or image
    assert value(solver.commit) == GitCommit(MAKE.SHA_IK_SOLVER)
    assert isinstance(solver.commit, Known) and isinstance(solver.commit.provenance, Provenance)
    assert isinstance(solver.commit.provenance.evidence.locator[-1], Span)
    assert isinstance(planner.release, Unknown)  # the editable root locks no version
    assert codes(output) == ["software_identity_missing"]
    assert assertion(output) is AssertionKind.STATED


def test_poetry_and_cargo_locks_pin_git_commits() -> None:
    solver, serial = items(read("lockfiles/poetry.lock"))
    assert value(solver.commit) == GitCommit(MAKE.SHA_IK_SOLVER)
    assert serial.commit.state == "not_covered"
    _, port, trajectory = items(read("lockfiles/Cargo.lock"))
    assert value(port.release) == SemanticVersion("4.5.1")
    assert value(trajectory.commit) == GitCommit(MAKE.SHA_MAIN)
    bad = read("lockfiles/Cargo_bad.lock")
    assert value(items(bad)[1].release) == DeclaredVersion("4.5")
    assert codes(bad) == ["version_not_semver"]


def test_a_cut_lockfile_is_malformed() -> None:
    assert codes(read("lockfiles/uv_truncated.lock")) == ["malformed"]


def test_npm_locks_name_packages_by_folder_and_skip_links() -> None:
    output = read("lockfiles/package-lock.json")
    names = [value(item.name) for item in items(output)]
    assert names == ["operator-console", "roslib", "teleop", "@example/map"]
    teleop = items(output)[2]
    assert value(teleop.commit) == GitCommit(MAKE.SHA_DEV)
    assert codes(output) == []


def test_npm_v1_locks_are_read_in_pre_order() -> None:
    output = read("lockfiles/package-lock_v1.json")
    names = [value(item.name) for item in items(output)]
    assert names == ["legacy-console", "roslib", "eventemitter2", "teleop"]
    assert value(items(output)[3].commit) == GitCommit(MAKE.SHA_DEV)


def test_a_repeated_json_key_is_malformed_never_the_last_value() -> None:
    assert codes(read("lockfiles/package-lock_duplicate.json")) == ["malformed"]
    assert codes(read("sbom/duplicate.cdx.json")) == ["malformed"]


# --- Firmware ----------------------------------------------------------------------------------


def test_an_elf_carries_its_build_id_and_package_note() -> None:
    output = read("firmware/app.elf")
    (item,) = items(output)
    assert value(item.build) == BuildId(MAKE.BUILD_ID.hex())
    assert value(item.name) == "nav-node"
    assert value(item.release) == DeclaredVersion("1.2.0-1")
    assert assertion(output) is AssertionKind.OBSERVED
    assert codes(output) == []


def test_a_big_endian_elf_without_sections_is_read_through_its_note_segment() -> None:
    (item,) = items(read("firmware/app32be.elf"))
    assert value(item.build) == BuildId(MAKE.BUILD_ID[::-1].hex())


def test_elves_without_identity_or_cut_short_say_so() -> None:
    stripped = read("firmware/stripped.elf")
    (item,) = items(stripped)
    assert isinstance(item.build, Unknown)
    assert codes(stripped) == ["software_identity_missing"]
    assert "truncated" in codes(read("firmware/truncated.elf"))


def test_an_esp_idf_image_states_project_firmware_version_and_build() -> None:
    (item,) = items(read("firmware/esp_app.bin"))
    assert value(item.name) == "gripper_fw"
    assert value(item.release) == FirmwareVersion("v2.3.1-robot")
    assert value(item.build) == BuildId(MAKE.ESP_ELF_SHA256.hex())
    assert codes(read("firmware/esp_truncated.bin")) == ["truncated"]


def test_an_mcuboot_header_is_a_firmware_release() -> None:
    (item,) = items(read("firmware/mcuboot.bin"))
    assert value(item.release) == FirmwareVersion("1.4.0+12")
    cut = read("firmware/mcuboot_truncated.bin")
    assert len(items(cut)) == 1 and codes(cut) == ["truncated"]


def test_px4_and_ardupilot_files_give_board_commit_and_describe() -> None:
    (px4,) = items(read("firmware/firmware.px4"))
    assert value(px4.device) == "PX4_FMU_V6X"
    assert value(px4.commit) == GitCommit(MAKE.SHA_MAIN)  # git_hash, full
    assert value(px4.release) == DeclaredVersion(f"v1.15.0-12-g{MAKE.SHA_MAIN[:7]}")
    (apj,) = items(read("firmware/firmware.apj"))
    assert value(apj.device) == "CubeOrange"
    assert value(apj.commit) == GitCommit(MAKE.SHA_DEV[:8])  # describe --always: abbreviated
    assert isinstance(apj.release, Unknown)  # no tag named: no release


# --- Checkpoints -------------------------------------------------------------------------------


def test_a_checkpoint_is_identified_by_its_content_id_and_states_no_digest() -> None:
    output = read("checkpoints/policy.safetensors")
    (item,) = items(output)
    assert all(getattr(item, name).state == "not_covered" for name in ORACLE.FIELDS)
    data = ORACLE.fixture("checkpoints/policy.safetensors")
    assert record(output).provenance.evidence.source == content_id(data)  # its sha256
    assert codes(output) == []


def test_damaged_safetensors_are_findings() -> None:
    cut = read("checkpoints/policy_truncated.safetensors")
    assert len(items(cut)) == 1 and codes(cut) == ["truncated"]
    assert codes(read("checkpoints/policy_bad_header.safetensors")) == ["malformed"]
    head_cut = ORACLE.run(ORACLE.fixture("checkpoints/policy.safetensors")[:40])
    assert codes(head_cut) == ["truncated"]


def test_an_onnx_model_version_is_its_release_and_the_graph_is_skipped() -> None:
    (item,) = items(read("checkpoints/policy.onnx"))
    assert value(item.release) == DeclaredVersion("3")
    assert item.digest.state == "not_covered"
    unversioned = read("checkpoints/policy_noversion.onnx")
    assert codes(unversioned) == ["software_identity_missing"]
    cut = read("checkpoints/policy_truncated.onnx")
    assert len(items(cut)) == 1 and "truncated" in codes(cut)


def test_a_pytorch_archive_is_read_by_its_zip_directory_only() -> None:
    output = read("checkpoints/policy.pt")
    assert len(items(output)) == 1 and codes(output) == []
    cut = read("checkpoints/policy_truncated.pt")
    assert len(items(cut)) == 1 and codes(cut) == ["truncated"]


# --- SBOMs and image indexes -------------------------------------------------------------------


def test_cyclonedx_components_keep_their_kinds() -> None:
    output = read("sbom/robot.cdx.json")
    stack, policy, nav, motor, eigen, blas, sidecar = items(output)
    assert value(stack.release) == DeclaredVersion("4.2.0")
    # SHA-256 is chosen over the SHA-512 listed first: it is what content ids are.
    assert value(policy.digest) == ModelCheckpointHash(HashAlgorithm.SHA256, MAKE.POLICY_SHA256)
    assert value(nav.digest) == ContainerImageDigest(f"sha256:{MAKE.NAV_DIGEST}")
    assert value(motor.release) == FirmwareVersion("0x010E")
    assert value(eigen.release) == DeclaredVersion("3.4.0")
    assert value(blas.name) == "eigen-blas" and isinstance(blas.release, Unknown)
    assert isinstance(sidecar.digest, Unknown) and eigen.digest.state == "not_applicable"
    assert codes(output) == ["software_identity_missing", "software_identity_missing"]


def test_spdx_packages_give_digests_firmware_and_no_assertion() -> None:
    output = read("sbom/robot.spdx.json")
    image, lidar, libyaml = items(output)
    assert value(image.digest) == ContainerImageDigest(MAKE.IMAGE_DIGEST)
    assert value(lidar.release) == FirmwareVersion("3.0.7")
    assert isinstance(libyaml.release, Unknown)  # NOASSERTION
    assert codes(output) == ["software_identity_missing"]


def test_an_oci_index_is_an_item_per_manifest_digest() -> None:
    output = read("sbom/index.json")
    arm64, amd64 = items(output)
    assert value(arm64.digest) == ContainerImageDigest(MAKE.IMAGE_DIGEST)
    assert value(arm64.name) == "amr-runtime"
    assert value(arm64.release) == DeclaredVersion("1.2.0")
    assert arm64.commit.state == "not_covered"  # image.revision is VCS-agnostic: in the bytes
    assert value(amd64.digest) == ContainerImageDigest(MAKE.IMAGE_DIGEST_AMD64)
    bad = read("sbom/index_bad_digest.json")
    assert isinstance(items(bad)[1].digest, Unknown)
    assert codes(bad) == ["invalid_value", "software_identity_missing"]
