"""The lifecycle mapper over packages the compiler wrote from real small exports (ADR 0002).

The packages under ``fixtures/lifecycle/packages`` are ``neptune ingest`` output, regenerated by
``make_fixture_packages.py``; these tests read them and never run ingestion. Every citation is
resolved back to the raw export's bytes here, with the standard library as the oracle.
"""

import csv
import hashlib
import io
import json
from collections.abc import Iterator
from dataclasses import replace
from fractions import Fraction
from pathlib import Path
from typing import Any

import pytest

from neptune.identity.hashing import content_id
from neptune.model.knowledge import AssertionKind, Known, KnownAbsent, NotApplicable, Unknown
from neptune.model.lifecycle import LIFECYCLE_KINDS
from neptune.model.provenance import ByteRange, JsonPointer, Provenance, RowCell, Span
from neptune.model.time import Timescale
from neptune.store.package import IngestPackage, package_files, read_files, read_package
from neptune_deploy.lifecycle import (
    MAPPER_ID,
    MAPPER_VERSION,
    LifecycleMapping,
    MappingError,
    load_mapping,
    map_files,
    map_package,
    parse_mapping,
    preset,
)
from neptune_deploy.lifecycle.cli import main

FIXTURES = Path(__file__).parent / "fixtures" / "lifecycle"
REQUALIFICATION = FIXTURES / "mappings" / "cell3_requalification.json"
ARCHETYPES: dict[str, tuple[str, ...]] = {
    "warehouse_amr": ("cmms_generic", "jira_json", "register_zone"),
    "manipulator_cell": ("servicenow_csv", "linear_csv", "register_risk", "register_asset"),
    "inspection_quadruped": ("cmms_maximo",),
}


def _base(name: str) -> IngestPackage:
    return read_package(FIXTURES / "packages" / name)


def _mappings(name: str) -> list[LifecycleMapping]:
    mappings = [preset(p) for p in ARCHETYPES[name]]
    if name == "manipulator_cell":
        mappings.append(load_mapping(REQUALIFICATION))
    return mappings


def _mapped(name: str) -> IngestPackage:
    return read_files(map_files(_base(name), _mappings(name)))


def _of(package: IngestPackage, kind: str) -> list[Any]:
    return [r for r in package.records if r.kind == kind]


def _codes(package: IngestPackage) -> dict[str, list[Any]]:
    out: dict[str, list[Any]] = {}
    for finding in _of(package, "ingest_finding"):
        out.setdefault(finding.code.split(".")[-1], []).append(finding)
    return out


def _place(state: Any) -> tuple[Any, ...]:
    """The locator a state's own provenance cites."""
    assert isinstance(state.provenance, Provenance)
    return state.provenance.evidence.locator


def _by_id(package: IngestPackage, kind: str, namespace: str, value: str) -> list[Any]:
    return [
        r
        for r in _of(package, kind)
        if any(
            isinstance(i, Known) and (i.value.namespace, i.value.value) == (namespace, value)
            for i in r.identifiers
        )
    ]


# --- Citations resolve to the exact source bytes -------------------------------------------------


def _raw(name: str, package: IngestPackage) -> dict[str, bytes]:
    paths = {r.content_id: r.location.path for r in _of(package, "source_revision")}
    return {source: (FIXTURES / name / path).read_bytes() for source, path in paths.items()}


def _resolve(raw: bytes, locator: tuple[Any, ...]) -> Any:
    """What a citation points at, read with the standard library."""
    first = locator[0]
    if isinstance(first, RowCell):
        rows = list(csv.reader(io.StringIO(raw.decode("utf-8", errors="replace"), newline="")))
        text = rows[first.row][first.column]
        assert first.column_name == rows[0][first.column]
        if len(locator) == 2:
            span = locator[1]
            assert isinstance(span, Span)
            return text[span.start : span.end]
        return text
    assert isinstance(first, ByteRange) and isinstance(locator[1], JsonPointer)
    value = json.loads(raw[first.offset : first.offset + first.length])
    for token in locator[1].pointer.split("/")[1:]:
        value = value[int(token)] if isinstance(value, list) else value[token]
    return value


def _states(value: Any) -> Iterator[Any]:
    """Every Knowledge state inside a record's fields."""
    if isinstance(value, Known | Unknown | KnownAbsent):
        yield value
    elif isinstance(value, tuple):
        for item in value:
            yield from _states(item)
    elif hasattr(value, "__dataclass_fields__") and not hasattr(value, "kind"):
        for name in value.__dataclass_fields__:
            yield from _states(getattr(value, name))


def _record_states(record: Any) -> Iterator[Any]:
    for name in record.__dataclass_fields__:
        if name not in ("id", "provenance"):
            yield from _states(getattr(record, name))


@pytest.mark.parametrize("name", sorted(ARCHETYPES))
def test_every_known_value_is_the_text_of_the_cell_it_cites(name: str) -> None:
    package = _mapped(name)
    raw = _raw(name, package)
    checked = 0
    for kind in LIFECYCLE_KINDS:
        for record in _of(package, kind.kind):
            assert record.provenance.assertion_kind is AssertionKind.STATED
            for state in _record_states(record):
                if not isinstance(state, Known) or not isinstance(state.provenance, Provenance):
                    continue
                evidence = state.provenance.evidence
                assert state.provenance.assertion_kind is AssertionKind.STATED
                assert isinstance(evidence.source, str)
                cited = _resolve(raw[evidence.source], evidence.locator)
                value = state.value
                if hasattr(value, "namespace"):
                    value = value.value
                elif hasattr(value, "value") and isinstance(value.value, str):
                    value = value.value  # a version
                if isinstance(value, float):
                    assert float(cited) == value
                elif isinstance(value, str):
                    assert cited == value
                checked += 1
    assert checked > 10


# --- The warehouse AMR fleet --------------------------------------------------------------------


def test_amr_work_orders_keep_parts_serials_and_firmware_as_declared() -> None:
    package = _mapped("warehouse_amr")
    (event,) = _by_id(package, "maintenance_event", "cmms.work_order", "WO-26-0311")
    (part,) = event.parts
    assert part.part.value == "Drive wheel assembly"
    assert [i.value.value for i in part.removed] == ["DW-11873"]
    assert [i.value.value for i in part.installed] == ["DW-12990"]
    assert event.configuration.value.namespace == "firmware"
    assert event.configuration.value.value == "4.2.0"
    assert [a.value for a in event.actions] == ["Replace drive wheel", "Clean lidar window"]
    assert event.actions[1].provenance.evidence.locator[-1] == Span(21, 39)
    assert [m.value.value for m in event.machines] == ["AMR-07"]
    # A work order with no part swapped lists none, and says so.
    twins = _by_id(package, "maintenance_event", "cmms.work_order", "WO-26-0313")
    (flash,) = [t for t in twins if t.machines[0].value.value == "AMR-07"]
    assert flash.parts == ()
    assert "item_blank" in _codes(package)
    assert [r.value.value for r in flash.related] == ["CHG-0042", "INC-0007"]


def test_civil_times_keep_their_own_clock_and_record_the_declared_zone() -> None:
    package = _mapped("warehouse_amr")
    (event,) = _by_id(package, "maintenance_event", "cmms.work_order", "WO-26-0311")
    stamp = event.performed.value
    # 2026-03-02 09:40 on its own civil clock, never moved to UTC.
    assert stamp.ticks == 20514 * 86400 + 9 * 3600 + 40 * 60
    (domain,) = [d for d in _of(package, "timestamp_domain") if d.id == stamp.domain_id]
    assert domain.field == "Completed"
    assert domain.scope == ()  # the declared zone is the mapping's, never the clock's scope
    assert isinstance(domain.timescale, Unknown)
    assert domain.resolution == Known(Fraction(1))


def test_stated_offsets_are_instants_on_a_posix_clock() -> None:
    package = _mapped("warehouse_amr")
    (incident,) = _by_id(package, "incident_record", "jira.issue", "INC-0007")
    stamp = incident.occurred.value
    # 2026-03-01T13:42:10.000+0100 is 12:42:10Z, in milliseconds.
    assert stamp.ticks == (20513 * 86400 + 12 * 3600 + 42 * 60 + 10) * 1000
    (domain,) = [d for d in _of(package, "timestamp_domain") if d.id == stamp.domain_id]
    assert domain.timescale == Known(Timescale.POSIX)
    assert domain.scope == ()
    assert domain.resolution == Known(Fraction(1, 1000))
    assert incident.severity.value == "S2"
    assert incident.location.value == "Aisle 14, outbound dock"


def test_zone_register_splits_declared_lists_and_keeps_units() -> None:
    package = _mapped("warehouse_amr")
    (envelope,) = _by_id(package, "authorisation_envelope", "register.envelope", "ENV-S007-03")
    assert [m.value.value for m in envelope.machines] == ["AMR-07", "AMR-09", "AMR-12"]
    assert all(isinstance(m.provenance.evidence.locator[-1], Span) for m in envelope.machines)
    (zone,) = envelope.zones
    assert zone.zone.value.value == "DOCK-1"
    assert zone.speed_limit.value.value == 0.8
    assert zone.speed_limit.unit.value.factors == (("m", 1), ("s", -1))
    assert envelope.supervision.value == "remote, 1 operator : 5 robots"
    assert [m.value for m in envelope.missions] == ["Pallet transfer", "Charging"]


def test_malformed_rows_are_findings_never_dropped_or_merged() -> None:
    package = _mapped("warehouse_amr")
    codes = _codes(package)
    # Duplicated work-order ids: both records kept, one finding naming the second.
    twins = _by_id(package, "maintenance_event", "cmms.work_order", "WO-26-0313")
    assert len(twins) == 2
    (repeated,) = codes["identifier_repeated"]
    assert repeated.records[0] in {t.id for t in twins}
    # A missing completion date is Unknown citing its cell, and the column is required.
    missing = next(t for t in twins if t.machines[0].value.value == "AMR-09")
    assert isinstance(missing.performed, Unknown)
    assert _place(missing.performed) == (RowCell(4, 4, "Completed"),)
    assert codes["value_blank"][0].details["rows"] == [4]
    # A date in another format than declared is not guessed.
    (late,) = _by_id(package, "maintenance_event", "cmms.work_order", "WO-26-0315")
    assert isinstance(late.performed, Unknown)
    assert codes["value_unreadable"][0].details["rows"] == [6]
    # A work order type the mapping does not name, and a column it does not map.
    rows = sorted(r for f in codes["row_unmatched"] for r in f.details["rows"])
    assert rows == [2, 5]  # the Jira task (array index 2) and the INSP work order (row 5)
    columns = sorted(c for f in codes["column_unmapped"] for c in f.details["columns"])
    assert columns == ["/fields/customfield_10040", "Downtime h"]


# --- The manipulator cell ------------------------------------------------------------------------


def test_cell_change_log_and_requalification_tests() -> None:
    package = _mapped("manipulator_cell")
    (change,) = _by_id(package, "change_record", "servicenow.change", "CHG0030012")
    (item,) = change.changes
    assert (item.category.value, item.before.value, item.after.value) == (
        "Software",
        "5.4.2",
        "5.6.0",
    )
    assert change.approval.decision.value == "approved"
    (requal,) = _by_id(package, "requalification_record", "plant2.requalification", "RQ-2026-004")
    assert [(t.name.value, t.result.value) for t in requal.tests] == [
        ("Joint brake test", "PASS"),
        ("Safety-rated speed monitoring 250 mm/s", "PASS"),
        ("Light curtain stop distance", "212 mm"),
    ]
    assert requal.return_to_service.decision.value == "Returned to service"
    (domain,) = [
        d for d in _of(package, "timestamp_domain") if d.id == requal.performed.value.domain_id
    ]
    assert domain.scope == ()
    (transform,) = [
        t for t in _of(package, "transform_record") if t.id == domain.provenance.transform
    ]
    assert transform.config["mapping"]["zone"] == "Europe/Berlin"


def test_mixed_encoding_cell_stays_unknown_and_a_missing_date_is_a_finding() -> None:
    base = _base("manipulator_cell")
    assert any(f.code == "tabular.invalid_utf8" for f in _of(base, "ingest_finding"))
    package = _mapped("manipulator_cell")
    (requal,) = _by_id(package, "requalification_record", "plant2.requalification", "RQ-2026-005")
    authority = requal.return_to_service.authority
    assert isinstance(authority, Unknown)
    assert _place(authority) == (RowCell(2, 14, "Decided By"),)
    assert isinstance(requal.return_to_service.time, Unknown)
    assert len(requal.tests) == 2  # the third test's cells are blank
    assert _codes(package)["value_blank"][0].details["column"] == "Decided On"


def test_risk_register_scores_are_named_by_their_columns() -> None:
    package = _mapped("manipulator_cell")
    (risk,) = _by_id(package, "risk_assessment", "register.risk_assessment", "RA-CELL3-01")
    (hazard,) = risk.hazards
    assert [(s.name, s.value.value) for s in hazard.scores] == [
        ("Severity", "S2"),
        ("Exposure", "F1"),
        ("Avoidance", "P2"),
        ("PLr", "d"),
    ]
    assert risk.method.value == "ISO 12100"
    (baseline,) = _of(package, "commissioning_baseline")
    assert [h.name.value for h in baseline.hardware] == [
        "Arm controller CR-7",
        "Parallel gripper PG-80",
    ]
    assert baseline.software[0].version.value.value == "5.4.2"
    assert [c.value for c in baseline.constraints] == [
        "No operation above 35 °C",
        "Manual loading only with light curtain active",
    ]


def test_every_archetype_maps_and_all_eight_kinds_appear() -> None:
    kinds: set[str] = set()
    for name in ARCHETYPES:
        package = _mapped(name)
        kinds |= {r.kind for r in package.records}
        severe = [f for f in _of(package, "ingest_finding") if f.severity == "error"]
        assert severe == []
    assert {kind.kind for kind in LIFECYCLE_KINDS} <= kinds


def test_legged_robot_maximo_export_maps_with_the_vendor_preset() -> None:
    package = _mapped("inspection_quadruped")
    (event,) = _by_id(package, "maintenance_event", "maximo.wonum", "WO1043")
    assert [i.value.value for i in event.parts[0].installed] == ["KA3-00577"]
    (calibration,) = _by_id(package, "maintenance_event", "maximo.wonum", "WO1044")
    assert calibration.parts == ()
    assert calibration.related == ()


# --- Lineage and determinism ---------------------------------------------------------------------


def test_transform_names_mapper_mapping_hash_and_base_package() -> None:
    base = _base("warehouse_amr")
    mapping = preset("cmms_generic")
    package = read_files(map_files(base, [mapping]))
    transforms = {t.id: t for t in _of(package, "transform_record")}
    (mapper,) = [t for t in transforms.values() if t.config.get("mapping_sha256")]
    assert (mapper.adapter_id, mapper.adapter_version) == (MAPPER_ID, MAPPER_VERSION)
    assert mapper.config["base_package"] == base.id
    assert mapper.config["mapping_sha256"] == mapping.sha256
    (upstream,) = mapper.upstream
    assert transforms[upstream].adapter_id == "tabular"
    # The tables no mapping applies to are findings of a run transform, not silence.
    unmapped = _codes(package)["table_unmapped"]
    assert len(unmapped) == 2


def test_same_inputs_give_byte_identical_packages_in_any_order() -> None:
    base = _base("manipulator_cell")
    mappings = _mappings("manipulator_cell")
    first = map_files(base, mappings)
    assert map_files(base, list(reversed(mappings))) == first
    assert map_files(_base("manipulator_cell"), mappings) == first


def test_a_changed_mapping_is_new_lineage() -> None:
    base = _base("warehouse_amr")
    original = preset("cmms_generic")
    document = dict(original.document)
    document["version"] = "2"
    changed = parse_mapping(json.dumps(document).encode())
    old = {r.id for r in _of(read_files(map_files(base, [original])), "maintenance_event")}
    new = {r.id for r in _of(read_files(map_files(base, [changed])), "maintenance_event")}
    assert old and new and not old & new


def _tree(root: Path) -> dict[str, str]:
    return {
        str(p.relative_to(root)): hashlib.sha256(p.read_bytes()).hexdigest()
        for p in sorted(root.rglob("*"))
        if p.is_file()
    }


def test_map_package_writes_a_readable_package_and_leaves_the_base_untouched(
    tmp_path: Path,
) -> None:
    root = FIXTURES / "packages" / "warehouse_amr"
    before = _tree(root)
    package_id = map_package(root, [preset("cmms_generic")], tmp_path / "out")
    assert _tree(root) == before
    written = read_package(tmp_path / "out")
    assert written.id == package_id
    assert written.manifest.version == 3


# --- Rules, tables and the command line ----------------------------------------------------------


def _rule_mapping(rules: list[dict[str, Any]]) -> LifecycleMapping:
    return parse_mapping(
        json.dumps(
            {
                "schema": "neptune-deploy.lifecycle-mapping/1",
                "id": "test.rules",
                "version": "1",
                "zone": "unstated",
                "rules": rules,
            }
        ).encode()
    )


def test_a_row_two_rules_match_gets_no_record() -> None:
    rule = {
        "kind": "maintenance_event",
        "requires": ["WO Number"],
        "fields": {"identifiers": [{"column": "WO Number", "namespace": "wo"}]},
    }
    mapping = _rule_mapping([{**rule, "id": "a"}, {**rule, "id": "b"}])
    package = read_files(map_files(_base("warehouse_amr"), [mapping]))
    assert _of(package, "maintenance_event") == []
    (ambiguous,) = _codes(package)["rule_ambiguous"]
    assert ambiguous.details["count"] == 6
    assert ambiguous.severity == "error"


def test_a_table_with_an_undeclared_header_is_a_finding() -> None:
    base = _base("inspection_quadruped")
    records = [
        replace(r, header=Unknown(r.header.provenance)) if r.kind == "structured_table" else r
        for r in base.records
    ]
    unheaded = read_files(package_files(records))
    package = read_files(map_files(unheaded, [preset("cmms_maximo")]))
    assert _of(package, "maintenance_event") == []
    assert len(_codes(package)["header_undeclared"]) == 1


def test_a_table_declared_headerless_is_unmapped_not_undeclared() -> None:
    base = _base("inspection_quadruped")
    records = [
        replace(r, header=NotApplicable()) if r.kind == "structured_table" else r
        for r in base.records
    ]
    package = read_files(map_files(read_files(package_files(records)), [preset("cmms_maximo")]))
    codes = _codes(package)
    assert "header_undeclared" not in codes
    assert len(codes["table_unmapped"]) == 1


def test_a_mapped_column_the_table_lacks_is_not_covered() -> None:
    mapping = _rule_mapping(
        [
            {
                "id": "wo",
                "kind": "maintenance_event",
                "requires": ["WONUM"],
                "fields": {"diagnosis": {"column": "Problem statement"}},
            }
        ]
    )
    package = read_files(map_files(_base("inspection_quadruped"), [mapping]))
    events = _of(package, "maintenance_event")
    assert len(events) == 2
    assert all(type(e.diagnosis).__name__ == "NotCovered" for e in events)
    (absent,) = _codes(package)["column_absent"]
    assert absent.details["column"] == "Problem statement"
    assert absent.details["count"] == 1  # one column, however many rows read it


def test_cli_maps_with_presets_and_files(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    out = tmp_path / "cell"
    code = main(
        [
            "map",
            str(FIXTURES / "packages" / "manipulator_cell"),
            "--preset",
            "servicenow_csv",
            "--mapping",
            str(REQUALIFICATION),
            "--out",
            str(out),
        ]
    )
    assert code == 0
    assert str(read_package(out).id) in capsys.readouterr().out


def test_cli_refuses_a_bad_mapping_and_a_missing_package(tmp_path: Path) -> None:
    bad = tmp_path / "bad.json"
    bad.write_bytes(b'{"schema": "nope"}')
    base = str(FIXTURES / "packages" / "warehouse_amr")
    assert main(["map", base, "--mapping", str(bad), "--out", str(tmp_path / "a")]) == 2
    assert main(["map", base, "--out", str(tmp_path / "b")]) == 2
    missing = str(tmp_path / "nothing")
    assert main(["map", missing, "--preset", "jira_json", "--out", str(tmp_path / "c")]) == 1


def test_mapping_twice_or_no_mapping_is_refused() -> None:
    base = _base("warehouse_amr")
    with pytest.raises(MappingError):
        map_files(base, [])
    with pytest.raises(MappingError):
        map_files(base, [preset("jira_json"), preset("jira_json")])


def test_fixture_bytes_match_the_packages_that_cite_them() -> None:
    for name in ARCHETYPES:
        package = _base(name)
        for revision in _of(package, "source_revision"):
            data = (FIXTURES / name / revision.location.path).read_bytes()
            assert content_id(data) == revision.content_id
