"""ROS 2 diagnostics through a declared vendor mapping, over compiler packages (ADR 0010 §7).

``legged_patrol`` is the compiler's package of a JSON export of a legged inspection robot's
``/diagnostics`` (read by the tabular adapter). ``arm_cell_bag`` is the compiler's package of a
manipulator cell's rosbag2, whose ``/diagnostics`` payloads the compiler does not decode into the
package yet. Both are ``neptune ingest`` output regenerated by ``make_fleet_ops_fixtures.py``;
these tests read them and never run ingestion, and never open the bag.
"""

import json
from pathlib import Path
from typing import Any

import pytest

from neptune.model.kinds import RECORD_KINDS
from neptune.model.knowledge import AssertionKind, Known, Unknown
from neptune.model.provenance import ByteRange, JsonPointer
from neptune.store.package import IngestPackage, read_files, read_package
from neptune_deploy import PACKAGE_SCHEMA_VERSION
from neptune_deploy.diagnostics import (
    FINDINGS,
    PRESETS,
    MappingError,
    load_mapping,
    map_diagnostics_files,
    parse_mapping,
    preset,
)

FIXTURES = Path(__file__).parent / "fixtures" / "fleet_ops" / "diagnostics"
VENDOR = FIXTURES / "mappings" / "vendor_legged.json"
EXPORT = FIXTURES / "legged_patrol" / "diagnostics_export.json"


def base(name: str) -> IngestPackage:
    return read_package(FIXTURES / "packages" / name)


def mapped(name: str = "legged_patrol", mapping: Any = None) -> IngestPackage:
    chosen = mapping or load_mapping(VENDOR)
    return read_files(map_diagnostics_files(base(name), [chosen]))


def of(package: IngestPackage, kind: str) -> list[Any]:
    return [r for r in package.records if r.kind == kind]


def codes(package: IngestPackage) -> dict[str, list[Any]]:
    out: dict[str, list[Any]] = {}
    for finding in of(package, "ingest_finding"):
        if finding.code.startswith("deploy_diagnostics_map."):
            out.setdefault(finding.code.split(".")[-1], []).append(finding)
    return out


def table(package: IngestPackage, name: str) -> tuple[Any, list[Any]]:
    (found,) = [t for t in of(package, "structured_table") if t.name.value == name]
    rows = sorted(
        (r for r in of(package, "structured_record") if r.table == found.id), key=lambda r: r.row
    )
    return found, rows


def column(found: Any, rows: list[Any], name: str) -> list[Any]:
    at = found.header.value.index(name)
    return [r.cells[at] for r in rows]


def test_a_status_is_an_event_row_with_the_kind_the_mapping_declares() -> None:
    out = mapped()
    events, rows = table(out, "diagnostic events")
    assert len(rows) == 6  # three arrays, with 2, 3 and 1 statuses
    kinds = {c.value if isinstance(c, Known) else None for c in column(events, rows, "event_kind")}
    assert kinds == {
        "diagnostic.ok",
        "diagnostic.error",
        "diagnostic.stale",
        "power.battery_state",  # the name is mapped: it wins over the level
        None,  # the code 4 and the status with no level
    }
    names = [c.value for c in column(events, rows, "name")]
    assert names == [  # the export's own order
        "/legged/foot_pad_fl",
        "/legged/battery",
        "/legged/foot_pad_fl",
        "/legged/vendor_gait",
        "/legged/lidar",
        "/legged/imu",
    ]
    battery = names.index("/legged/battery")
    assert column(events, rows, "event_kind")[battery].value == "power.battery_state"
    assert column(events, rows, "level")[battery].value == 1  # still the integer the export wrote


def test_a_code_outside_the_mapping_is_a_finding_and_stays_as_declared() -> None:
    out = mapped()
    events, rows = table(out, "diagnostic events")
    gait = next(
        r for r in rows if r.cells[events.header.value.index("name")].value == "/legged/vendor_gait"
    )
    assert isinstance(gait.cells[0], Unknown)  # no kind is guessed
    assert gait.cells[events.header.value.index("level")].value == 4  # as declared
    (unmapped,) = codes(out)["status_unmapped"]
    assert unmapped.details["level"] == "4" and unmapped.details["count"] == 1
    assert unmapped.records == (gait.id,)  # it qualifies exactly that record
    # The finding cites the level cell of the status in the export, at its exact place.
    place = unmapped.subject
    assert isinstance(place.locator[0], ByteRange)
    assert place.locator[-1] == JsonPointer("/status/1/level")
    # The value in the values table is untouched.
    values, vrows = table(out, "diagnostic values")
    keys = [c.value for c in column(values, vrows, "key")]
    assert "state_code" in keys
    assert codes(out)["level_missing"][0].details["rows"] == [2]


def test_every_cell_cites_its_cell_in_the_export_stated_under_the_mapping_transform() -> None:
    out = mapped()
    raw = json.loads(EXPORT.read_text())
    (transform,) = [
        t for t in of(out, "transform_record") if t.adapter_id == "deploy_diagnostics_map"
    ]
    (artifact,) = of(out, "source_artifact")
    events, rows = table(out, "diagnostic events")
    at = events.header.value.index("name")
    # The status number each row cites, in the export's own order: array by array, status by status.
    expected = [
        (array, status) for array, entry in enumerate(raw) for status in range(len(entry["status"]))
    ]
    for row, (array, status) in zip(rows, expected, strict=True):
        assert row.provenance.assertion_kind is AssertionKind.STATED
        assert row.provenance.transform == transform.id
        for cell in row.cells:
            assert cell.provenance.transform == transform.id
        place = row.cells[at].provenance.evidence
        assert place.source == artifact.content_id
        assert place.locator[-1] == JsonPointer(f"/status/{status}/name")
        # The place holds exactly the text the cell states.
        assert raw[array]["status"][status]["name"] == row.cells[at].value


def test_the_header_stamp_is_a_named_clock_declared_by_the_mapping_only() -> None:
    out = mapped()
    (clock,) = of(out, "timestamp_domain")
    assert clock.field == "header.stamp"
    assert clock.epoch.value == "unix" and clock.role.value == "sample"
    assert str(clock.resolution.value) == "1/1000000000"
    (plain,) = of(mapped(mapping=_without_clock()), "timestamp_domain")
    for name in ("role", "epoch", "timescale", "resolution"):
        assert isinstance(getattr(plain, name), Unknown), name
    events, rows = table(out, "diagnostic events")
    companions = column(events, rows, "@clock:stamp")
    assert {c.value for c in companions if isinstance(c, Known)} == {clock.id}
    assert [c.value for c in column(events, rows, "stamp.sec")][:2] == [1772468400, 1772468400]
    assert column(events, rows, "stamp.nanosec")[0].value == 125000000  # as stated, not combined


def _without_clock() -> Any:
    data = json.loads(VENDOR.read_text())
    data.pop("clock")
    data["id"] = "acme.no-clock"
    return parse_mapping(json.dumps(data).encode())


def test_a_bags_diagnostics_stream_is_a_finding_and_the_bag_is_never_opened() -> None:
    package = base("arm_cell_bag")
    streams = [s for s in package.records if s.kind == "stream"]
    assert {s.topic.value for s in streams} == {"/diagnostics", "/joint_states"}
    out = mapped("arm_cell_bag", preset("ros2_diagnostics"))
    (finding,) = codes(out)["bag_payload_not_decoded"]
    assert finding.details["topic"] == "/diagnostics" and finding.details["message_count"] == 6
    diag = next(s for s in streams if s.topic.value == "/diagnostics")
    assert finding.records == (diag.id,)
    assert [t for t in of(out, "structured_table") if t.name.value == "diagnostic events"] == []
    assert "nothing_to_map" not in codes(out)


def test_a_package_with_no_diagnostics_says_so() -> None:
    other = read_package(
        Path(__file__).parent / "fixtures" / "lifecycle" / "packages" / "manipulator_cell"
    )
    out = read_files(map_diagnostics_files(other, [preset("ros2_diagnostics")]))
    assert list(codes(out)) == ["nothing_to_map"]


def test_the_shipped_preset_declares_ros2s_own_codes_and_registers_no_vocabulary() -> None:
    assert PRESETS == ("ros2_diagnostics",)
    mapping = preset("ros2_diagnostics")
    assert dict(mapping.levels) == {
        "0": "diagnostic.ok",
        "1": "diagnostic.warn",
        "2": "diagnostic.error",
        "3": "diagnostic.stale",
    }
    assert mapping.vendor == "ros2" and dict(mapping.names) == {}
    out = mapped("legged_patrol", mapping)
    assert set(codes(out)) == {"status_unmapped", "level_missing"}


def test_the_mapping_is_part_of_the_transform_so_a_new_mapping_is_new_lineage() -> None:
    a = mapped(mapping=preset("ros2_diagnostics"))
    b = mapped(mapping=load_mapping(VENDOR))
    assert not {r.id for r in of(a, "structured_record")} & {
        r.id for r in of(b, "structured_record")
    }
    (ta,) = [t for t in of(a, "transform_record") if t.adapter_id == "deploy_diagnostics_map"]
    assert ta.config["mapping"] == preset("ros2_diagnostics").sha256
    assert ta.config["vendor"] == "ros2" and ta.upstream  # lineage to the tabular adapter


def test_the_result_is_byte_identical_and_the_base_is_never_changed() -> None:
    package = base("legged_patrol")
    before = package.files()
    first = map_diagnostics_files(package, [load_mapping(VENDOR)])
    second = map_diagnostics_files(base("legged_patrol"), [load_mapping(VENDOR)])
    assert first == second
    assert package.files() == before


def test_every_record_round_trips_the_compilers_strict_readers() -> None:
    out = mapped()
    assert PACKAGE_SCHEMA_VERSION == 4
    for record in out.records:
        assert RECORD_KINDS[record.kind][1](record.to_json()) == record


@pytest.mark.parametrize(
    "change",
    [
        {"schema": "other/1"},
        {"id": "Not A Token"},
        {"array": "status"},
        {"levels": {}},
        {"levels": {"07": "x"}},
        {"levels": {"x": "diagnostic.ok"}},
        {"levels": {"0": ""}},
        {"levels": {"0": "line\nbreak"}},
        {"names": {"/a": 7}},
        {"stamp": {"sec": "/a"}},
        {"clock": {"resolution": "0"}},
        {"fields": {"level": "bad key"}},
        {"fields": {"colour": "x"}},
        {"topics": "/diagnostics"},
        {"unknown": 1},
    ],
)
def test_a_wrong_mapping_file_fails_loudly_before_any_record_is_read(
    change: dict[str, Any],
) -> None:
    data = {**json.loads(VENDOR.read_text()), **change}
    with pytest.raises(MappingError):
        parse_mapping(json.dumps(data).encode())
    with pytest.raises(MappingError):
        parse_mapping(b"not json")

    with pytest.raises(MappingError):
        parse_mapping(b"[]")
    with pytest.raises(MappingError):
        parse_mapping(b" " * (1024 * 1024 + 1))
    with pytest.raises(MappingError):
        map_diagnostics_files(base("legged_patrol"), [])
    with pytest.raises(MappingError):
        map_diagnostics_files(base("legged_patrol"), [load_mapping(VENDOR), load_mapping(VENDOR)])


def test_the_finding_catalogue_is_what_the_mapper_can_report() -> None:
    assert set(FINDINGS) == {
        "status_unmapped",
        "level_missing",
        "bag_payload_not_decoded",
        "nothing_to_map",
    }


def test_a_mapping_file_is_read_to_its_limit_and_no_further(tmp_path: Path) -> None:
    huge = tmp_path / "huge.json"
    huge.write_bytes(b" " * (4 * 1024 * 1024))
    with pytest.raises(MappingError, match="at most"):
        load_mapping(huge)


def test_a_mapping_file_is_strict_json() -> None:
    text = VENDOR.read_text()
    repeated = text.replace('"0": "diagnostic.ok",', '"0": "diagnostic.ok", "0": "other",')
    assert repeated != text
    with pytest.raises(MappingError, match="strict"):  # a repeated key has two readings
        parse_mapping(repeated.encode())
    with pytest.raises(MappingError, match="strict"):
        parse_mapping(text.replace('"version": "2"', '"version": NaN').encode())
    with pytest.raises(MappingError, match="strict"):
        parse_mapping(text.replace('"version": "2"', '"version": 1e999').encode())
