"""The document mapper over packages the compiler wrote from small PDFs and Markdown (ADR 0003).

The packages under ``fixtures/documents/packages`` are ``neptune ingest`` output, regenerated by
``make_document_fixtures.py``; these tests read them and never run ingestion. Every citation is
resolved back to the page text the compiler extracted (the block spans of ADR 0038 §3), or for
Markdown to the file's own bytes, and compared with what the record states.
"""

from collections.abc import Iterator
from dataclasses import replace
from datetime import date, datetime
from pathlib import Path
from typing import Any

import pytest

from neptune.model.knowledge import (
    AssertionKind,
    Known,
    KnownAbsent,
    NotCovered,
    Unknown,
)
from neptune.model.provenance import ByteRange, EvidenceRef, Page, Span
from neptune.model.versions import DeclaredVersion, FirmwareVersion
from neptune.store.package import IngestPackage, read_files, read_package
from neptune_deploy.lifecycle import (
    DOCUMENT_MAPPER_ID,
    DocumentTemplate,
    TemplateRegistry,
    map_files,
)

FIXTURES = Path(__file__).parent / "fixtures" / "documents"
TEMPLATES = FIXTURES / "templates"
EPOCH = date(1970, 1, 1)


def _base(name: str) -> IngestPackage:
    return read_package(FIXTURES / "packages" / name)


def _templates() -> list[DocumentTemplate]:
    return list(TemplateRegistry.from_paths([TEMPLATES]).templates())


def _mapped(base: IngestPackage, templates: list[DocumentTemplate] | None = None) -> IngestPackage:
    return read_files(map_files(base, templates=templates or _templates()))


def _of(package: IngestPackage, kind: str) -> list[Any]:
    return [r for r in package.records if r.kind == kind]


def _codes(package: IngestPackage) -> dict[str, list[Any]]:
    out: dict[str, list[Any]] = {}
    for finding in _of(package, "ingest_finding"):
        assert finding.code.startswith(f"{DOCUMENT_MAPPER_ID}.")
        out.setdefault(finding.code.split(".")[-1], []).append(finding)
    return out


def _one(package: IngestPackage, kind: str) -> Any:
    (record,) = _of(package, kind)
    return record


def _raw(name: str, package: IngestPackage) -> dict[Any, bytes]:
    paths = {r.content_id: r.location.path for r in _of(package, "source_revision")}
    return {
        source: (FIXTURES / "sources" / name / path).read_bytes() for source, path in paths.items()
    }


class _Oracle:
    """What a citation points at: the compiler's page text for a PDF (each block's text then LF, in
    reading order: ADR 0038 §3), the file's own text for Markdown."""

    def __init__(self, name: str, base: IngestPackage) -> None:
        self.raw = _raw(name, base)
        self.pages: dict[tuple[Any, int | None], str] = {}
        by_page: dict[tuple[Any, int | None], list[Any]] = {}
        for block in sorted(_of(base, "document_block"), key=lambda b: b.order):
            evidence = block.provenance.evidence
            first = evidence.locator[0]
            page = first.index if isinstance(first, Page) else None
            by_page.setdefault((evidence.source, page), []).append(block)
        for key, blocks in by_page.items():
            if key[1] is not None:
                self.pages[key] = "".join(
                    (b.text.value if isinstance(b.text, Known) else "￼") + "\n" for b in blocks
                )

    def text(self, evidence: EvidenceRef) -> str:
        steps: list[Any] = list(evidence.locator)
        page = None
        if isinstance(steps[0], Page):
            page = steps.pop(0).index
        if page is None:
            text = self.raw[evidence.source].decode("utf-8")
        else:
            text = self.pages[(evidence.source, page)]
        for step in steps:
            assert isinstance(step, Span), step
            text = text[step.start : step.end]
        return text


def _states(value: Any) -> Iterator[Any]:
    """Every Knowledge state inside a record's fields; a Known list is structure, not a value."""
    if isinstance(value, Known) and isinstance(value.value, tuple):
        yield from _states(value.value)
    elif isinstance(value, Known | Unknown | KnownAbsent | NotCovered):
        yield value
    elif isinstance(value, tuple):
        for item in value:
            yield from _states(item)
    elif hasattr(value, "__dataclass_fields__") and not hasattr(value, "kind"):
        for name in value.__dataclass_fields__:
            yield from _states(getattr(value, name))


def _record_states(record: Any) -> Iterator[Any]:
    for name in record.__dataclass_fields__:
        if name not in ("id", "provenance"):
            yield from _states(getattr(record, name))


def _days(text: str, pattern: str = "%Y-%m-%d") -> int:
    return (datetime.strptime(text, pattern).date() - EPOCH).days


def _seconds(text: str) -> int:
    """Seconds from 1970-01-01T00:00:00 of the text's own civil clock, never moved to UTC."""
    return int((datetime.strptime(text, "%Y-%m-%d %H:%M") - datetime(1970, 1, 1)).total_seconds())


ARCHETYPES = {
    "warehouse_amr": {"risk_assessment": 1, "incident_record": 1},
    "manipulator_cell": {"risk_assessment": 1, "commissioning_baseline": 1},
    "inspection_quadruped": {"maintenance_event": 2},
}


@pytest.mark.parametrize("name", sorted(ARCHETYPES))
def test_each_archetype_maps_to_its_records_and_every_document_matches(name: str) -> None:
    package = _mapped(_base(name))
    for kind, count in ARCHETYPES[name].items():
        assert len(_of(package, kind)) == count, kind
    matched = _codes(package)["template_matched"]
    assert len(matched) == sum(ARCHETYPES[name].values())
    assert {f.severity for f in matched} == {"info"}


@pytest.mark.parametrize("name", sorted(ARCHETYPES))
def test_every_known_value_is_the_text_of_the_span_or_cell_it_cites(name: str) -> None:
    base = _base(name)
    oracle = _Oracle(name, base)
    package = _mapped(base)
    checked = 0
    for kind in ARCHETYPES[name]:
        for record in _of(package, kind):
            assert record.provenance.assertion_kind is AssertionKind.STATED
            for state in _record_states(record):
                if not isinstance(state, Known):
                    continue
                provenance: Any = state.provenance
                assert provenance.assertion_kind is AssertionKind.STATED
                cited = oracle.text(provenance.evidence)
                value = state.value
                if hasattr(value, "namespace"):
                    assert cited == value.value
                elif isinstance(value, str):
                    assert cited == value
                elif hasattr(value, "ticks"):
                    assert cited and cited[0].isdigit()
                else:
                    assert cited == value.value  # a declared version
                checked += 1
    assert checked > 20


def test_the_oracle_agrees_with_every_block_the_compiler_cut() -> None:
    for name in ARCHETYPES:
        base = _base(name)
        oracle = _Oracle(name, base)
        blocks = [b for b in _of(base, "document_block") if isinstance(b.text, Known)]
        assert blocks
        for block in blocks:
            assert oracle.text(block.provenance.evidence) == block.text.value


# --- Risk assessments: two formats -----------------------------------------------------------


def test_the_amr_risk_assessment_is_parsed_as_declared() -> None:
    package = _mapped(_base("warehouse_amr"))
    risk = _one(package, "risk_assessment")
    assert [i.value for i in risk.identifiers.value] == [_id("hh.risk_assessment", "RA-AMR-0417")]
    assert risk.site.value.value == "HH-DC2"
    assert [m.value.value for m in risk.machines.value] == ["AMR-07", "AMR-08"]
    assert risk.method.value == "ISO 3691-4 risk estimation (severity, exposure, avoidance)"
    assert risk.assessed.value.ticks == _days("2026-03-12")
    assert risk.approval.decision.value == "Accepted with conditions"
    assert risk.approval.authority.value == "Site safety lead"
    assert risk.approval.time.value.ticks == _days("2026-03-14")
    assert isinstance(risk.configuration, NotCovered) and isinstance(
        risk.related, NotCovered
    )  # no section lists them
    hazards = risk.hazards.value
    assert [h.hazard.value for h in hazards] == [
        "Collision with a pedestrian in a shared aisle",
        "Fork contact with a rack during pallet pick",
        "Battery thermal event while charging",
    ]
    for hazard in hazards:
        assert [s.name for s in hazard.scores.value] == [
            "Severity",
            "Exposure",
            "Avoidance",
            "Risk reduction",
        ]
    # Scores are the table's own text: never ranked, never converted.
    assert [[s.value.value for s in h.scores.value] for h in hazards] == [
        ["S3", "E2", "A2", "PLr d"],
        ["S2", "E2", "A1", "PLr c"],
        ["S3", "E1", "A2", "PLr c"],
    ]
    assert [m.value for m in hazards[0].mitigations.value] == [
        "Personnel-detecting scanner",
        "speed limited to 1.2 m/s in aisle zones",
    ]


def _id(namespace: str, value: str) -> Any:
    from neptune.model.ids import LogicalId

    return LogicalId(namespace, value)


def test_the_cell_risk_assessment_reads_a_headerless_table_and_its_own_column_names() -> None:
    package = _mapped(_base("manipulator_cell"))
    risk = _one(package, "risk_assessment")
    assert risk.identifiers.value[0].value.value == "CELL3-RA-009"
    assert risk.site.value.value == "Cell 3, Line 2"
    assert [m.value.value for m in risk.machines.value] == ["R1 6-axis", "R2 6-axis"]
    # Day-first, as the template declares: 12 March 2026, not 3 December.
    assert risk.assessed.value.ticks == _days("12/03/2026", "%d/%m/%Y")
    assert risk.approval.decision.value == "Approved"
    assert risk.approval.time.value.ticks == _days("14/03/2026", "%d/%m/%Y")
    names = [[s.name for s in h.scores.value] for h in risk.hazards.value]
    assert names == [["Severity of injury", "Exposure", "Avoidance", "Risk level"]] * 3
    assert [s.value.value for s in risk.hazards.value[1].scores.value] == [
        "Serious",
        "Seldom",
        "Possible",
        "Medium",
    ]
    assert [m.value for m in risk.hazards.value[2].mitigations.value] == [
        "Reduced speed 250 mm/s",
        "enabling switch",
    ]


def test_a_column_no_field_reads_and_a_row_nobody_read_are_findings_not_silence() -> None:
    package = _mapped(_base("manipulator_cell"))
    codes = _codes(package)
    (column,) = codes["column_unmapped"]
    assert column.details["columns"] == ["Task"] and column.severity == "warning"
    unread = [f for f in codes["text_unread"] if f.details["template"] == "risk.robot_cell"]
    (finding,) = unread
    assert finding.details["count"] == 1
    oracle = _Oracle("manipulator_cell", _base("manipulator_cell"))
    assert [oracle.text(ref) for ref in finding.related] == ["Revision\tB"]


def test_the_two_risk_formats_make_the_same_kind_from_different_structure() -> None:
    amr = _one(_mapped(_base("warehouse_amr")), "risk_assessment")
    cell = _one(_mapped(_base("manipulator_cell")), "risk_assessment")
    assert type(amr) is type(cell)
    assert [s.name for s in amr.hazards.value[0].scores.value] != [
        s.name for s in cell.hazards.value[0].scores.value
    ]


# --- Commissioning, incident, SOP ------------------------------------------------------------


def test_the_commissioning_report_maps_inventories_tests_constraints_and_sign_off() -> None:
    base = _base("manipulator_cell")
    oracle = _Oracle("manipulator_cell", base)
    commissioning = _one(_mapped(base), "commissioning_baseline")
    assert commissioning.commissioned.value.ticks == _seconds("2026-02-20 16:30")
    assert commissioning.configuration.value.value == "cfg-c3-1.4"
    assert [i.name.value for i in commissioning.hardware.value] == [
        "Manipulator R1",
        "Controller R1",
        "Gripper",
    ]
    controller = commissioning.hardware.value[1]
    assert controller.model.value == "OmniCore C30"
    assert controller.identifiers.value[0].value.value == "SN-C30-552"
    assert controller.version.value == FirmwareVersion("7.8.1")
    assert [(i.name.value, i.version.value) for i in commissioning.software.value] == [
        ("Palletising application", DeclaredVersion("1.4.0")),
        ("Safety configuration", DeclaredVersion("2026.02-a")),
    ]
    assert [c.value.value for c in commissioning.calibrations.value] == ["CAL-C3-001", "CAL-C3-002"]
    assert [(t.name.value, t.result.value) for t in commissioning.tests.value] == [
        ("Safety-rated monitored stop", "PASS"),
        ("Light curtain response", "PASS 142 ms"),
        ("Palletising cycle, 50 pallets", "PASS"),
    ]
    assert commissioning.tests.value[2].performed.value.ticks == _seconds("2026-02-20 14:15")
    assert [c.value for c in commissioning.constraints.value] == [
        "Payload not above 35 kg",
        "Pallet gate closed during automatic mode",
    ]
    # Each statement cites its own list item.
    assert [oracle.text(c.provenance.evidence) for c in commissioning.constraints.value] == [
        c.value for c in commissioning.constraints.value
    ]
    assert commissioning.sign_off.decision.value == "Accepted"
    assert commissioning.sign_off.time.value.ticks == _seconds("2026-02-21 09:10")


def test_the_incident_report_keeps_free_text_as_cited_spans_and_reads_its_timeline() -> None:
    base = _base("warehouse_amr")
    oracle = _Oracle("warehouse_amr", base)
    incident = _one(_mapped(base), "incident_record")
    assert incident.severity.value == "Minor, no injury"
    assert incident.zone.value.value == "Z3"
    assert incident.location.value == "Aisle 14, rack face B"
    assert [a.value.value for a in incident.assets.value] == ["PAL-5521", "RACK-14B"]
    assert incident.related.value[0].value.value == "RA-AMR-0417"
    assert incident.occurred.value.ticks == _seconds("2026-04-02 14:07")
    assert [(e.time.value.ticks, e.text.value) for e in incident.timeline.value] == [
        (_seconds("2026-04-02 14:05"), "AMR-07 starts pallet pick in aisle 14"),
        (_seconds("2026-04-02 14:07"), "Fork contacts rack upright; protective stop"),
        (_seconds("2026-04-02 14:09"), "Fleet manager flags AMR-07 as blocked"),
        (_seconds("2026-04-02 14:31"), "Technician clears the aisle and resets"),
    ]
    blocks = {b.provenance.evidence: b.text.value for b in _of(base, "document_block")}
    description, root_cause = incident.description, incident.root_cause
    # Verbatim: the description is the compiler's two paragraphs, one LF apart, as one span.
    assert description.value == (
        "While lifting pallet PAL-5521 the left fork touched the rack upright and the\n"
        "mast stopped. The pallet stayed on the forks.\n"
        "No person was in the aisle. The aisle was closed for 24 minutes."
    )
    assert oracle.text(description.provenance.evidence) == description.value
    first = description.provenance.evidence
    assert any(
        ref.locator[0] == first.locator[0] and _starts(ref) == _starts(first) for ref in blocks
    )
    assert root_cause.value == (
        "The rack face was 40 mm further out than the site map. The pick position\n"
        "had not been refreshed after the rack was re-bolted on 2026-03-28."
    )
    assert blocks[_block_of(blocks, root_cause.provenance.evidence)] == root_cause.value


def _starts(evidence: EvidenceRef) -> int:
    span = evidence.locator[-1]
    assert isinstance(span, Span)
    return span.start


def _block_of(blocks: dict[EvidenceRef, str], evidence: EvidenceRef) -> EvidenceRef:
    (found,) = [ref for ref in blocks if ref == evidence]
    return found


def test_the_sop_becomes_a_maintenance_event_from_a_pdf_and_from_markdown() -> None:
    package = _mapped(_base("inspection_quadruped"))
    events = _of(package, "maintenance_event")
    by_wo = {e.identifiers.value[0].value.value: e for e in events}
    assert set(by_wo) == {"WO-QD-5521", "WO-QD-6107"}
    pdf, markdown = by_wo["WO-QD-5521"], by_wo["WO-QD-6107"]
    for event in (pdf, markdown):
        assert (
            event.actions.value[0].value == "Power the robot down and place it on the service stand"
        )
        assert len(event.actions.value) == 4
        assert event.related.value[0].value.value == "SOP-MP-031"
        assert isinstance(event.site, NotCovered)
    assert pdf.performed.value.ticks == _days("2026-05-08")
    assert markdown.performed.value.ticks == _days("2026-05-19")
    assert [p.part.value for p in pdf.parts.value] == ["Foot pad FL", "Retaining screw set"]
    assert pdf.parts.value[0].removed.value[0].value.value == "FP-0183"
    assert pdf.parts.value[0].installed.value[0].value.value == "FP-0291"
    assert [p.part.value for p in markdown.parts.value] == ["Foot pad RR"]
    assert markdown.diagnosis.value == "Foot pad cracked on leg RR"
    # Markdown cites byte-for-byte spans of the file itself: no page.
    assert all(
        not isinstance(s.provenance.evidence.locator[0], Page)
        for s in _states(markdown.actions.value)
    )


def test_a_procedure_is_not_an_event_so_an_sop_without_a_work_record_does_not_match() -> None:
    base = _base("inspection_quadruped")
    records = tuple(
        replace(r, text=Known("Work order name: x", r.text.provenance))
        if r.kind == "document_block"
        and isinstance(r.text, Known)
        and r.text.value.startswith("Work order:")
        else r
        for r in base.records
    )
    package = _mapped(replace(base, records=records))
    assert _of(package, "maintenance_event") == []
    assert len(_codes(package)["document_unmatched"]) == 2


# --- Matching is an observation --------------------------------------------------------------


def test_a_match_is_an_observation_that_cites_the_structure_it_saw() -> None:
    base = _base("warehouse_amr")
    oracle = _Oracle("warehouse_amr", base)
    package = _mapped(base)
    risk = _one(package, "risk_assessment")
    finding = next(
        f
        for f in _codes(package)["template_matched"]
        if f.details["template"] == "risk.amr_iso3691_4"
    )
    assert finding.severity == "info"
    assert finding.records == (risk.id,)
    assert finding.subject == risk.provenance.evidence
    assert isinstance(finding.subject.locator[0], ByteRange)
    assert finding.details["version"] == "2"
    assert finding.details["not_covered"] == ["configuration", "related"]
    seen = [oracle.text(ref) for ref in finding.related]
    assert seen == [
        "RA-3691-AMR",
        "2",
        "RA-AMR-0417",
        "Hazard analysis",
        "Hazard\tSeverity\tExposure\tAvoidance\tRisk reduction\tMitigation",
    ]


def test_a_field_the_template_does_not_cover_is_not_covered_never_blank() -> None:
    package = _mapped(_base("warehouse_amr"))
    incident = _one(package, "incident_record")
    assert isinstance(incident.configuration, NotCovered)
    risk = _one(package, "risk_assessment")
    assert isinstance(risk.configuration, NotCovered)
    # A label the template names but the document lacks is also not covered, with a finding.
    base = _base("warehouse_amr")
    records = tuple(
        replace(r, text=Known("Zones: Z3", r.text.provenance))
        if r.kind == "document_block" and isinstance(r.text, Known) and r.text.value == "Zone: Z3"
        else r
        for r in base.records
    )
    package = _mapped(replace(base, records=records))
    assert isinstance(_one(package, "incident_record").zone, NotCovered)
    (absent,) = _codes(package)["label_absent"]
    assert absent.details["reference"] == "Zone" and absent.severity == "info"
