"""Peak memory of the software adapter on one hostile input at its size limit (ADR 0040 §11).

Usage: ``python measure_peak_memory.py <case>``. Prints JSON: ``peak_mib`` (the process's peak
resident set, interpreter and imports included), the finding codes and the bytes read. It runs in
a process of its own so the peak is this input's. ``CASES`` names every input; each is built at
the size where the adapter would read it (the script cap or the document cap).
"""

import json
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Final

from neptune.adapters.harness import ingest_source
from neptune.adapters.software import SoftwareAdapter
from neptune.discovery.reader import BytesReader

MIB: Final = 1024 * 1024
DOC: Final = 8 * MIB - 1024  # under max_document_bytes
SCRIPT: Final = 256 * 1024 - 1024  # under max_script_bytes


def repeat(head: bytes, unit: bytes, size: int) -> bytes:
    return head + unit * ((size - len(head)) // len(unit))


def cargo() -> bytes:
    head = (
        b"# This file is automatically @generated by Cargo.\n"
        b"# It is not intended for manual editing.\nversion = 4\n\n"
    )
    return repeat(head, b'[[package]]\nname = "a"\nversion = "1.0.0"\n', DOC)


def cargo_empty_tables() -> bytes:
    """One inline array of empty tables: tomllib holds a dict per two bytes before any reader."""
    head = (
        b"# This file is automatically @generated by Cargo.\n"
        b"# It is not intended for manual editing.\nversion = 4\n\npackage = ["
    )
    return repeat(head, b"{},", DOC) + b"]\n"


def poetry_named_tables() -> bytes:
    head = b"# This file is automatically @generated by Poetry 1.8.0 and should not be changed.\n"
    return repeat(head + b"package = [", b'{name="a"},', DOC) + b"]\n"


def setup_nested_operators() -> bytes:
    """A chain the Python parser's own stack cannot hold (it raises MemoryError)."""
    return b'from setuptools import setup\nsetup(name="a", version=' + b"-" * 100_000 + b"1)\n"


def uv() -> bytes:
    head = b'version = 1\nrequires-python = ">=3.11"\n\n'
    return repeat(head, b'[[package]]\nname = "a"\nversion = "1"\n', DOC)


def cmake() -> bytes:
    head = b"cmake_minimum_required(VERSION 3.16)\n"
    return repeat(head, b"project(a VERSION 1.0)\n", SCRIPT)


def cmake_arguments() -> bytes:
    head = b"cmake_minimum_required(VERSION 3.16)\nproject(a "
    return repeat(head, b"VERSION 1 ", SCRIPT) + b")\n"


def setup_calls() -> bytes:
    return repeat(b"from setuptools import setup\n", b'setup(name="a", version="1")\n', SCRIPT)


def setup_expression() -> bytes:
    head = b'from setuptools import setup\nsetup(name="a", version="1", x=['
    return repeat(head, b"f(),", SCRIPT) + b"])\n"


def packed_refs() -> bytes:
    return repeat(b"", b"a" * 40 + b" refs/heads/b\n", DOC)


def packed_tags() -> bytes:
    return repeat(b"", b"a" * 40 + b" refs/tags/b\n", DOC)


def package_xml_names() -> bytes:
    body = b"".join(b"<name>n%d</name>" % i for i in range(DOC // 22))
    return b'<package format="3">' + body + b"</package>"


def npm_lock() -> bytes:
    entries = b",".join(b'"node_modules/p%d":{"version":"1.0.0"}' % i for i in range(DOC // 44))
    return b'{"lockfileVersion":3,"packages":{' + entries + b"}}"


def npm_lock_junk() -> bytes:
    entries = b",".join(b'"p%d":1' % i for i in range(DOC // 12))
    return b'{"lockfileVersion":1,"dependencies":{' + entries + b"}}"


def cyclonedx() -> bytes:
    head = b'{"bomFormat":"CycloneDX","specVersion":"1.5","components":['
    return head + b",".join([b'{"name":"a","version":"1"}'] * (DOC // 28)) + b"]}"


def safetensors_junk() -> bytes:
    import struct

    header = json.dumps({f"t{i}": "x" for i in range(DOC // 20)}).encode()
    return struct.pack("<Q", len(header)) + header


def elf_notes() -> bytes:
    from importlib.util import module_from_spec, spec_from_file_location

    path = Path(__file__).parent / "make_software_fixtures.py"
    spec = spec_from_file_location("make_software_fixtures", path)
    assert spec is not None and spec.loader is not None
    make = module_from_spec(spec)
    spec.loader.exec_module(make)
    notes = b"".join(make._note(b"GNU\x00", 3, i.to_bytes(4, "little") * 5) for i in range(200_000))
    elf: bytes = make.elf64([(b".note.test", notes)])
    return elf


CASES: Final[dict[str, Callable[[], bytes]]] = {
    "cargo": cargo,
    "cargo_empty_tables": cargo_empty_tables,
    "poetry_named_tables": poetry_named_tables,
    "setup_nested_operators": setup_nested_operators,
    "uv": uv,
    "cmake": cmake,
    "cmake_arguments": cmake_arguments,
    "setup_calls": setup_calls,
    "setup_expression": setup_expression,
    "packed_refs": packed_refs,
    "packed_tags": packed_tags,
    "package_xml_names": package_xml_names,
    "npm_lock": npm_lock,
    "npm_lock_junk": npm_lock_junk,
    "cyclonedx": cyclonedx,
    "safetensors_junk": safetensors_junk,
    "elf_notes": elf_notes,
}


def peak_mib() -> int:
    """This process's peak resident set (``VmHWM``). ``ru_maxrss`` is not used: a child inherits
    its parent's peak across the fork, so it would measure the test runner, not the input."""
    for line in Path("/proc/self/status").read_text().splitlines():
        if line.startswith("VmHWM:"):
            return int(line.split()[1]) // 1024  # kB
    raise OSError("VmHWM is not available: this measurement needs Linux")


def main(name: str) -> None:
    data = CASES[name]()
    output = ingest_source(SoftwareAdapter(), BytesReader(data), {})
    peak = peak_mib()
    codes = sorted({finding.code.removeprefix("software.") for finding in output.findings()})
    sys.stdout.write(json.dumps({"bytes": len(data), "codes": codes, "peak_mib": peak}) + "\n")


if __name__ == "__main__":
    main(sys.argv[1])
